### ISSUE TITLE
How do I let request logger do error log on those DeadlineExceeded status responses?

### ISSUE THREAD

**Issue by liufuyang** [einride/cloudrunner-go#352]
Seems a bit confusing about `REQUESTLOGGER_CODETOLEVEL` and `REQUESTLOGGER_STATUSTOLEVEL` on which to use and how to exactly use it, perhaps one can just set it like `REQUESTLOGGER_CODETOLEVEL=DeadlineExceeded:ErrorLevel`?

**Comment by odsod** [comment]
@liufuyang Did you come to an answer here? The map handling is the same as https://github.com/kelseyhightower/envconfig - you can see the handling here - https://github.com/einride/cloudrunner-go/blob/master/cloudconfig/envconfig.go#L231-L251 - it should work like you say in your example.
